version: '3.7'
services:
  mysql:
    image: mysql:5.7
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    env_file:
      - .env.docker-compose

  app:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    env_file:
      - .env.docker-compose
    depends_on:
      - mysql